
tcamMemWrapper_64x28:
    tcamBlocks: 4
    moduleName: "top_tcam_mem"
    instanceName: "tcam7x64"
    wireBlockSel:
        name: block_sel
        width: 4
        inputAddr: [9, 8]
    wireWriteMask:
        name: wmask
        width: 4
    wireAwAddr:
        name: aw_addr
        width: 8
    wireVtbAddr:
        name: vtb_addr
        width: 7
    wireOutRData:
        name: out_rdata
        width: 64
    ports:
    -   name: "in_clk"
        direction: "input"
        width: 0
    -   name: "in_csb"
        direction: "input"
        width: 0
    -   name: "in_web"
        direction: "input"
        width: 0
    -   name: "in_wmask"
        direction: "input"
        width: 4
    -   name: "in_addr"
        direction: "input"
        width: 28
    -   name: "in_wdata"
        direction: "input"
        width: 32
    -   name: "out_pma"
        direction: "output"
        width: 6